# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 16:37
from __future__ import unicode_literals

import consulting.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('slug', models.SlugField(help_text=b'Determines the URL. Do not change this after an item is published.', max_length=40, unique=True)),
                ('title', models.CharField(help_text=b'Short name of client, used throughout site.', max_length=40, unique=True)),
                ('organization', models.CharField(blank=True, help_text=b'Organization full name. Used on detail page. If blank, title is used.', max_length=70)),
                ('image', models.ImageField(blank=True, help_text=b'Logo for client, which is resized automatically . Make as square as possible.', upload_to=consulting.models.client_upload_to)),
                ('description', models.TextField(help_text=b'Short description of client and work. Show on listing and detail page.')),
                ('body', models.TextField(blank=True, help_text=b'Full text. Appears on client detail page.')),
                ('url', models.URLField(blank=True, help_text=b"URL for this client (don't forget the http://).", max_length=100, verbose_name=b'URL')),
                ('position', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ClientReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=40, verbose_name=b'name')),
                ('job_title', models.CharField(max_length=40)),
                ('phone', models.CharField(blank=True, help_text=b'Not shown to site viewers.', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulting.Client')),
            ],
            options={
                'ordering': ['position', 'created'],
            },
        ),
        migrations.CreateModel(
            name='ClientWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(help_text=b'Short description of work. Shows up in bold on client detail page.')),
                ('body', models.TextField(blank=True, help_text=b'Long description of work. Shows up on client detail page.')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulting.Client')),
                ('references', models.ManyToManyField(blank=True, help_text=b'References for this client work.', to='consulting.ClientReference')),
            ],
            options={
                'ordering': ['position', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('slug', models.SlugField(help_text=b'Determines the URL. Do not change this after an item is published.', max_length=20, unique=True)),
                ('title', models.CharField(max_length=40, unique=True, verbose_name=b'name')),
                ('photo', models.ImageField(blank=True, help_text=b'Resized automatically. Make as square as possible.', upload_to=b'consultants')),
                ('description', models.TextField(help_text=b'Short description of consultant. Shows on listing page and detail page.')),
                ('body', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LibraryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('slug', models.SlugField(help_text=b'Determines the URL. Do not change this after an item is published.', unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(help_text=b'Description of category. Shows up on listing page and detail page.')),
                ('position', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['position', 'title'],
                'verbose_name_plural': 'library categories',
            },
        ),
        migrations.CreateModel(
            name='LibraryFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('slug', models.SlugField(help_text=b'Determines the URL. Do not change this after an item is published.', max_length=100, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(default=b'<p>hello</p>', help_text=b'Description of file/link. Shows up on category detail page.')),
                ('asset', models.FileField(blank=True, help_text=b'File asset.', max_length=255, upload_to=consulting.models.file_upload_to)),
                ('url', models.URLField(blank=True, help_text=b"Link URL (don't forget the http://)", max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=100)),
                ('librarycategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulting.LibraryCategory', verbose_name=b'library category')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('slug', models.SlugField(help_text=b'Determines the URL. Do not change this after an item is published.', max_length=25, unique=True)),
                ('title', models.CharField(max_length=40, unique=True)),
                ('short_description', models.CharField(help_text=b'Appears on home page carousel.', max_length=100, unique=True)),
                ('icon_name', models.CharField(help_text=b'Font Awesome icon name (without the leading "fa-").', max_length=15, unique=True)),
                ('description', models.TextField(help_text=b'Appears on listing page, but not on detail page.')),
                ('body', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='QAndA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('slug', models.SlugField(help_text=b'Determines the URL. Do not change this after an item is published.', unique=True)),
                ('title', models.CharField(help_text=b'Shows up in portlets, search results, and on the listing page.', max_length=75, unique=True)),
                ('description', models.TextField(help_text=b'Short description of the question. Shows up on the listing page.')),
                ('question', models.TextField(help_text=b'Full question. Shows on the detail page.')),
                ('answer', models.TextField()),
                ('credit', models.CharField(blank=True, help_text=b'Appears at bottom of answer. Used for providing publishing credit.', max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'ordering': ['position', '-id'],
                'verbose_name': 'Question and Answer',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', model_utils.fields.StatusField(choices=[(b'private', b'private'), (b'published', b'published')], default=b'private', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('quote', models.CharField(max_length=100)),
                ('author', models.CharField(help_text=b'Entire text for author, like "T.S. Eliot, Curmudgeon, Bank of England".', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=b'oliver@otessier.com', help_text=b'Email address shown on the site.', max_length=255)),
                ('about_footer', models.TextField(help_text=b'Appears in site footer.')),
                ('about_homepage', models.TextField(help_text=b'Appears on home page.')),
                ('phone', models.CharField(help_text=b'Appears in footer.', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='practiceareas',
            field=models.ManyToManyField(blank=True, to='consulting.PracticeArea', verbose_name=b'practice areas'),
        ),
        migrations.AlterUniqueTogether(
            name='clientwork',
            unique_together=set([('client', 'title')]),
        ),
        migrations.AlterUniqueTogether(
            name='clientreference',
            unique_together=set([('client', 'title')]),
        ),
    ]
