# Generated by Django 2.0 on 2017-12-24 03:24

import consulting.models
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_auto_20151220_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='body',
            field=models.TextField(blank=True, help_text='Full text. Appears on client detail page.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(help_text='Short description of client and work. Show on listing and detail page.'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, help_text='Logo for client, which is resized automatically . Make as square as possible.', upload_to=consulting.models.client_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization full name. Used on detail page. If blank, title is used.', max_length=70),
        ),
        migrations.AlterField(
            model_name='client',
            name='practiceareas',
            field=models.ManyToManyField(blank=True, to='consulting.PracticeArea', verbose_name='practice areas'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(help_text='Determines the URL. Do not change this after an item is published.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='title',
            field=models.CharField(help_text='Short name of client, used throughout site.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.URLField(blank=True, help_text="URL for this client (don't forget the http://).", max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='clientreference',
            name='phone',
            field=models.CharField(blank=True, help_text='Not shown to site viewers.', max_length=20),
        ),
        migrations.AlterField(
            model_name='clientreference',
            name='title',
            field=models.CharField(max_length=40, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='clientwork',
            name='body',
            field=models.TextField(blank=True, help_text='Long description of work. Shows up on client detail page.'),
        ),
        migrations.AlterField(
            model_name='clientwork',
            name='description',
            field=models.TextField(help_text='Short description of work. Shows up in bold on client detail page.'),
        ),
        migrations.AlterField(
            model_name='clientwork',
            name='references',
            field=models.ManyToManyField(blank=True, help_text='References for this client work.', to='consulting.ClientReference'),
        ),
        migrations.AlterField(
            model_name='clientwork',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='description',
            field=models.TextField(help_text='Short description of consultant. Shows on listing page and detail page.'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='photo',
            field=models.ImageField(blank=True, help_text='Resized automatically. Make as square as possible.', upload_to='consultants'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='slug',
            field=models.SlugField(help_text='Determines the URL. Do not change this after an item is published.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='librarycategory',
            name='description',
            field=models.TextField(help_text='Description of category. Shows up on listing page and detail page.'),
        ),
        migrations.AlterField(
            model_name='librarycategory',
            name='slug',
            field=models.SlugField(help_text='Determines the URL. Do not change this after an item is published.', unique=True),
        ),
        migrations.AlterField(
            model_name='librarycategory',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='asset',
            field=models.FileField(blank=True, help_text='File asset.', max_length=255, upload_to=consulting.models.file_upload_to),
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='description',
            field=models.TextField(default='<p>hello</p>', help_text='Description of file/link. Shows up on category detail page.'),
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='librarycategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulting.LibraryCategory', verbose_name='library category'),
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='slug',
            field=models.SlugField(help_text='Determines the URL. Do not change this after an item is published.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='libraryfile',
            name='url',
            field=models.URLField(blank=True, help_text="Link URL (don't forget the http://)", max_length=255),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='description',
            field=models.TextField(help_text='Appears on listing page, but not on detail page.'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='icon_name',
            field=models.CharField(help_text='Font Awesome icon name (without the leading "fa-").', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='short_description',
            field=models.CharField(help_text='Appears on home page carousel.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='slug',
            field=models.SlugField(help_text='Determines the URL. Do not change this after an item is published.', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='credit',
            field=models.CharField(blank=True, help_text='Appears at bottom of answer. Used for providing publishing credit.', max_length=100),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='description',
            field=models.TextField(help_text='Short description of the question. Shows up on the listing page.'),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='question',
            field=models.TextField(help_text='Full question. Shows on the detail page.'),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='slug',
            field=models.SlugField(help_text='Determines the URL. Do not change this after an item is published.', unique=True),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='qanda',
            name='title',
            field=models.CharField(help_text='Shows up in portlets, search results, and on the listing page.', max_length=75, unique=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(help_text='Entire text for author, like "T.S. Eliot, Curmudgeon, Bank of England".', max_length=75),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='private', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_footer',
            field=models.TextField(help_text='Appears in site footer.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='about_homepage',
            field=models.TextField(help_text='Appears on home page.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='email',
            field=models.EmailField(default='oliver@otessier.com', help_text='Email address shown on the site.', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='phone',
            field=models.CharField(help_text='Appears in footer.', max_length=20),
        ),
    ]
